#file: noinspection SpellCheckingInspection
debug: false

logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
  level:
    root: ${LOGGING_LEVEL_ROOT:"warn"}
    tomcat: "warn"
    web: "debug"
    sql: "debug"
    #    org.springframework: "trace"
    # detailed information about the files that are being loaded
    org.springframework.boot.context.config: "trace"
    org.springframework.boot.autoconfigure.condition: "debug"
    org.springframework.beans.factory.support: "info"
    org.springframework.orm.jpa: debug
    org.springframework.jdbc.datasource: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    microplatform: "trace"
    org:
      springframework:
        data: debug
        security: debug
        boot:
          autoconfigure:
            h2: debug
server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: fake


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    build:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
